server:
  port: 6004
langchain4j:
  open-ai:
    image-model:
      model-name: cogview-4-250304
      api-key: ${OPEN_AI_KEY}
      base-url: https://open.bigmodel.cn/api/paas/v4
      log-requests: true
      log-responses: true
    chat-model:
      model-name: qwen-plus
      api-key: ${AI_DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
    streaming-chat-model:
      model-name: qwen-plus
      api-key: ${AI_DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
    embedding-model:
      model-name: text-embedding-v3
      api-key: ${AI_DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
      max-segments-per-batch: 10
  community:
    redis:
      host: 8.138.246.2
      port: 6380

logging:
  level:
    dev.langchain4j: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.138.246.2:3306/campus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 998244353
  data:
    redis:
      host: 8.138.246.2
      port: 6380
      password: ${MYSQL_PASSWORD}
      lettuce:
        pool:
          max-active: 8  # 最大连接
          max-idle: 8    # 最大空闲连接
          min-idle: 0    # 最小空闲连接
          max-wait: 100  # 连接等待时间



mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
    - classpath:dao/*.xml
    - classpath:dao/**/*.xml

alipay:
  appId: 9021000132667513
  appPrivateKey: ${ALIPAY_PRIVATE_KEY}
  alipayPublicKey: ${ALIPAY_PUBLIC_KEY}
  notifyUrl: http://8.138.246.2:6004/alipay/notify

