server:
  port: 6004
spring:
  data:
    redis:
      host: 8.138.246.2
      port: 6379
      password: 1714083619
      lettuce:
        pool:
          max-active: 8  # 最大连接
          max-idle: 8    # 最大空闲连接
          min-idle: 0    # 最小空闲连接
          max-wait: 100  # 连接等待时间
  ai:
    zhipuai:
      api-key: 13ef7484d9d544cbafbe3c5ddfd37b58.uN8RrpSV7G4lil1m
      chat:
        options:
          model: cogview-4-250304
    chat:
      memory:
        repository:
          jdbc:
            platform: mysql
            initialize-schema: never

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.138.246.2:3306/campus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 998244353

logging:
  level:
    com.campus: debug
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: debug
  pattern:
    dateformat: HH:mm:ss:SSS


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
    - classpath:dao/*.xml
    - classpath:dao/**/*.xml

alipay:
  appId: 9021000132667513
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCKFNFnx5FWmDKMbiwa98gGbPbQZrJiH2ucQrrEb4gqGz4X+vrmY6nunoYym6U0alNzzp6jfsGDzkKwvEtPUZJZh6evbHg2t24gs9g/JL8WGeqj4EdBO6vLA+Fr60hGG8PSh4tzi7u5ARWnCUGqjDUVx3RkDohi8OlTXRq829xHaLCXhQ8EW2Ri47iiZrhBwsfAvbbgppzlKCJAnAvc6VKxC35g0SXfkwnL+xZAt8SKUdWdNZK6XM+JuFYQjVhuJnGiCQX6mv5QADufc+wdM3UfuO+Irsr7hhTFBQfc0CG5JIqiiYJvEYSNN9XuZBxWh4TpVvnNQmrNrnxz1nZUK8XpAgMBAAECggEARY7TJkpcJpko7aEaSsODWelONBFnzxIw7ViYKRheKYfrsbzW43RVSEVHKPtLL6pYO8BcHdReu30OD2XrMhvPc5ZonHAx5q5kpcizKKvkLsgDcWYrvurGUdC0n964W8jkzotFboF3oWywcaKyF63lmAEP2s+PWPgvMbV3IKhIwRd2mZrLVF3zdc/nEnnKc02+o7Y0YLxjM4OoMMuayCuFaBxPz8s63f89d0CxUxWXPzKeQnw9sqH4Xru6WckhycQ1h7PIEWmaqczwCzze48rk0olU1uvQ1IVTAvlRoKts9fol/goP4Mjv3YA6x+T5yvqJWvCf7uunwwbBgyDBEZUE4QKBgQDXnh4gyxZH+nOR3TCog/CXERlPPgKu1LvqT44KWvyvPn+zIpNqwWpPgSvjqc0RVom58uB70hlzh5iYwLxX+Cg8/kb6MwfJVE9KGsT7kuMVXsYCE/fBVkywshSYGr8d2uTnFjnoLOT1+U/1/XOt/Augb3+XFw/Lgqlq0UWWxXNLdQKBgQCj8S/uD0NIRJ5EX4+xoIIip7H9WQfeH0H9sBs87C/PMzIbw0f2IkiWI07MNCK24x9k/zD/5rr4IKzT/TTNgh7nNMDCtZ5fX2oWAjPgy0AB+lBfHcTTpFbIhUv+l5SPyodR2PQyGKqy2VJG4tgB6vmKVCPh8pNn7BKCuXRZ+sSmJQKBgG0UlgNbGsuRPdRmRU6LaTTTtq0rHupZvzN7yc0dWMZDZRE4BcI1VVYhcBW9+nux/v0ujTi3Ap860w08PEx4w8qPjVLYbDEDURWZU1w+ZFmUV7IHbgjGYwflH5wPs+4jpjfuO59kzvRNi5FUBqjXYP5qSe8jAJ+hW5opgv4SqBBdAoGAY+QFjEwIdvQ4avi/GT/viyYasX+Z56GsF+NB9XEEAH/1PC1Un4hsKe8BiDMMI9tnuaY0OPhhW+as584UalOqeL4P5ZO8F+iPPzHAYmv1aD8Y0ZvV3g74Qd3WXB4IC0UgBqLmx8930tnP5Bk7/I8r1TlHU9j2MBALh1NwrZK6V3ECgYEAk7u6KFBc+rZE+tw/mF/QuYw5/5Tk5ayGhfoE7N6QmzCyqyF1JslJIFkMLLeMRYgkLGdixth81R5gCkNBfJ2LUCJiKGmkh0u5N3oaL72N3AO5nBaPGDZFOQWHqAHIg1spY1YP1Zkqr+RiWuWXVpMCQXZLoGuT26cVaofHcW7aeUo=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjy382IxHw0v/QwxVQ5tcqyW/+e8dpNa1O0uOD7MWYSBTpYD/7qWkJcxSFR0HYo5i9ZpEfoBmVaaFbl+Pzfb5jye/fq5+uXcc8Gaar/+NBB2aj/jyJoa8PCc35rCFRZYmW0y2DQguJGFzRzkZiPt/coJN8iRrRtqsm5VEhxxQIL7pFSheS/p/pCtJu0W7w+x1+bvLJSiBwocdnOEg0otUAwA+bSzCCkjK05PAYFlhOuFft9b5+D4fxpx7GF0HpF+FoxF+bUDiTz8rIKk6HYFlPJEGwv9RF9VpchM3d4QZg/8hYI/DzzkvnPd+l2BEtictp9qCwxjjUXHLfJN0WjRDyQIDAQAB
  notifyUrl: http://8.138.246.2:6004/alipay/notify

