server:
  port: 6004
spring:
  data:
    redis:
      host: 8.138.246.2
      port: 6379
      password: 1714083619
      lettuce:
        pool:
          max-active: 8  # 最大连接
          max-idle: 8    # 最大空闲连接
          min-idle: 0    # 最小空闲连接
          max-wait: 100  # 连接等待时间
  ai:
    zhipuai:
      api-key: 13ef7484d9d544cbafbe3c5ddfd37b58.uN8RrpSV7G4lil1m
      chat:
        options:
          model: cogview-4-250304
    chat:
      memory:
        repository:
          jdbc:
            platform: mysql
            initialize-schema: never

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.138.246.2:3306/campus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 998244353

logging:
  level:
    com.campus: debug
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: debug
  pattern:
    dateformat: HH:mm:ss:SSS


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
    - classpath:dao/*.xml
    - classpath:dao/**/*.xml


